<?php

class JMGSeeder extends Seeder {

    public function run() {

        Rank::insert([
            ['name' => 'Master'],
            ['name' => '1st Officer/Chief mate'],
            ['name' => '2nd Officer'],
            ['name' => '3rd Officer'],
            ['name' => 'Deck Cadet'],
            ['name' => 'Bosun'],
            ['name' => 'Able Bodied Seaman(AB)/Quarter Master'],
            ['name' => 'Ordinary Seaman(OS)'],
            ['name' => 'General Purpose Deck'],
            ['name' => 'Chief Engineer'],
            ['name' => '2nd Engineer'],
            ['name' => '3rd Engineer'],
            ['name' => '4th Engineer'],
            ['name' => 'Engine Cadet'],
            ['name' => 'Electrician'],
            ['name' => 'Assistant Electrician'],
            ['name' => 'Engine Fitter'],
            ['name' => 'Pumpman'],
            ['name' => 'Oiler'],
            ['name' => 'Wiper/Motorman'],
            ['name' => 'Chief Cook'],
            ['name' => 'Assistant Cook'],
            ['name' => 'Messman'],
            ['name' => 'Chief Steward'],
            ['name' => 'Assistant Steward'],
            ['name' => 'Outlet and Room waiters'],
            ['name' => 'Chambermaids'],
            ['name' => 'Bellboys'],
            ['name' => 'Bakers'],
            ['name' => 'Barrista'],
            ['name' => 'Galley Cooks'],
            ['name' => 'Pastry Chefs'],
            ['name' => 'Galley Helpers'],
            ['name' => 'Room Stewards'],
            ['name' => 'Janitors'],
            ['name' => 'Nurses'],
            ['name' => 'Doctors'],
            ['name' => 'Florists'],
            ['name' => 'Security Officers'],
            ['name' => 'Tour Directors'],
            ['name' => 'Entertainers'],
            ['name' => 'Front and back officer workers'],
            ['name' => 'Rank'],
            ['name' => 'Rigger'],
            ['name' => 'Rigger Foreman'],
            ['name' => 'Welder'],
            ['name' => 'Sous Chef'],
            ['name' => 'Jr. Sous Chef'],
            ['name' => 'Chef de Partie'],
            ['name' => 'Chef de Partie Trainee'],
            ['name' => 'Assistant Chef de Partie'],
            ['name' => '1st Cook'],
            ['name' => '2nd Cook'],
            ['name' => '3rd Cook'],
            ['name' => 'Waiter/Waitress'],
            ['name' => 'Buffet Waiter'],
            ['name' => 'Assistant Waiter/Waitress'],
            ['name' => 'Assistant Buffet Waiter'],
            ['name' => 'Utility Snack'],
            ['name' => 'Utility Restaurant'],
            ['name' => 'Room Service Steward'],
            ['name' => 'Bartender'],
            ['name' => 'Assistant Bartender'],
            ['name' => 'Bar Waiter/Waitress'],
            ['name' => 'Deck Supervisor'],
            ['name' => 'Deck Steward'],
            ['name' => 'Sommelier'],
            ['name' => 'Confectioner'],
            ['name' => 'Chef de Partie Pastry'],
            ['name' => 'Pastry'],
            ['name' => 'Assistant Pastry'],
            ['name' => 'Head Baker'],
            ['name' => 'Assistant Baker'],
            ['name' => 'Butcher'],
            ['name' => 'Assistant Butcher'],
            ['name' => 'Head Storekeeper'],
            ['name' => 'Assistant Storekeeper'],
            ['name' => 'Store Utility'],
            ['name' => 'Head Cleaner'],
            ['name' => 'Utility Cleaner'],
            ['name' => 'Musician - Band Leader'],
            ['name' => 'Musician - Guitar'],
            ['name' => 'Musician - Bass'],
            ['name' => 'Musician -  Piano'],
            ['name' => 'House Keeping Supervisor'],
            ['name' => 'Officer Steward'],
            ['name' => 'Tailor'],
            ['name' => 'Linenkeeper'],
            ['name' => 'Assistant Linenkeeper'],
            ['name' => 'Night Auditor'],
            ['name' => 'Crew Admin'],
            ['name' => 'Crew Purser'],
            ['name' => 'Systems Manager'],
            ['name' => 'Admin Assistant'],
            ['name' => 'Hotel Inventory Controller'],
            ['name' => 'Hr Coordinator'],
            ['name' => 'Provision Master'],
            ['name' => 'Kitchen Steward'],
            ['name' => 'Crew Steward'],
            ['name' => 'Thai Massage Therapist'],
            ['name' => 'Spa Cleaner'],
            ['name' => 'Carpenter'],
            ['name' => 'Repairman'],
            ['name' => 'Technical Storekeeper'],
            ['name' => 'Deck Fitter'],
            ['name' => '1st Assistant Engineer'],
            ['name' => 'Second Assistant Engineer'],
            ['name' => 'Third Assistant Engineer'],
            ['name' => 'Boatswain'],
            ['name' => 'Deck Foreman'],
            ['name' => 'Radio Officer'],
            ['name' => '1st Engineer'],
            ['name' => 'Electrical Engineer'],
            ['name' => 'Oiler No. 1'],
            ['name' => '2nd Cook'],
            ['name' => 'Deck Boy'],
            ['name' => 'Engine Boy'],
            ['name' => 'Catering Boy'],
            ['name' => 'Deck Maintenance Attendant (DMA)'],
            ['name' => 'Engine Maintenance Attendant(EMA)'],
            ['name' => 'Cook'],
            ['name' => 'Commis Chef'],
            ['name' => 'Housekeeping Utility'],
            ['name' => 'Gas Engineer'],
            ['name' => 'Steward'],
            ['name' => 'Boat Captain'],
            ['name' => 'Junior Second Engineer']
            ]);

        Vessel::insert([
            ['name' => 'Bulk Carriers'],
            ['name' => 'Oil/Product Tankers'],
            ['name' => 'Refrigerated Cargo Ships'],
            ['name' => 'Livestock Carriers'],
            ['name' => 'Liquefied Natural Gas (LNG) Carrier'],
            ['name' => 'Car Carriers'],
            ['name' => 'Container Ships'],
            ['name' => 'Dry Cargo Vessels'],
            ['name' => 'Heavy Lift Vessels'],
            ['name' => 'Tugs'],
            ['name' => 'Ro-Ro Vessels'],
            ['name' => 'Passenger/Cruise Vessels'],
            ['name' => 'Chemical Tanker'],
            ['name' => 'General Cargo'],
            ['name' => 'Vessel'],
            ['name' => 'Offshore Vessels'],
            ['name' => 'Capesize'],
            ['name' => 'Panamax'],
            ['name' => 'Suezmax'],
            ['name' => 'Aframax'],
            ['name' => 'Kamsamax'],
            ['name' => 'Gantry Crane'],
            ['name' => 'Cable Ship'],
            ['name' => 'Reefer Vessel'],
            ['name' => 'Anchor Handling Tug Supply (AHTS)'],
            ['name' => 'Crew Boat'],
            ['name' => 'Livestock'],
            ['name' => 'Landing Craft Transporter']
            ]);

        TradeRoute::insert([
            ['name' => 'Asia'],
            ['name' => 'Africa'],
            ['name' => 'North America'],
            ['name' => 'South America'],
            ['name' => 'Central America'],
            ['name' => 'Europe'],
            ['name' => 'World Wide']
            ]);

    }

}
